apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: qa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: qa/mysql-secret
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: qa/mysql-secret
        property: MYSQL_DATABASE
    - secretKey: MYSQL_USER
      remoteRef:
        key: qa/mysql-secret
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: qa/mysql-secret
        property: MYSQL_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: qa/mysql-secret
        property: DATABASE_URL
